name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        uses: openzim/docker-publish-action@v7
        with:
          image-name: openzim/wp1_selection_tools
          registries: ghcr.io
          on-master: latest
          restrict-to: openzim/wp1_selection_tools
          credentials: |
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
